---
# vars file for roles/node_app
node_app_repo: "https://github.com/JustNormalProgrammer/SecureBox"
node_app_branch: "main"
db_port: 5432
db_host: "127.0.0.1"
node_app_port: 5000
node_app_env:
  NODE_ENV: "production"
  PORT: "{{ node_app_port }}"
  DATABASE_URL: "postgresql://{{ db_user }}:{{ db_password | urlencode }}@{{ db_host }}:{{ db_port }}/{{ db_name}}"
  SESSION_SECRET: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits length=32') }}"
  CORS_ORIGIN: "https://your-domain.com"
  EMAIL_USER: "{{ email_user }}"
  EMAIL_PASS: "{{ email_pass }}"
  EMAIL_HOST: "{{ email_host }}"
  DB_HOST: "{{ db_host }}"
  DB_PORT: "{{ db_port }}"
  DB_DATABASE: "{{ db_name }}"
  DB_USER: "{{ admin_user }}"
  DB_PASSWORD: "{{ admin_password }}"
  TOKEN_EXPIRATION_MINUTES: "30"
  SECRET_KEY: "{{ app_secret_key }}"
  DATABASE: "{{ db_name }}"
  DB_SSL: "false"

node_version: "22"



node_app_service_name: "nodeapp"
